### ISSUE TITLE
GLTC bus stop signs along route 3 do not indicate that they are on route 3

### ISSUE THREAD

**Issue by partytax** [Lynchburg-Urban-Network/lynchburg-road-issues#149]
Not one location, so not providing coordinates.

**Comment by partytax** [comment]
Circles on signs are **2.5 inches**

![signal-2024-01-30-124113_002](https://github.com/Lynchburg-Urban-Network/lynchburg-road-issues/assets/29897671/45d9bd05-57ea-40e5-9160-f62ee4d6e37a)

**Comment by partytax** [comment]
Considering premium matte outdoor stickers from Vinyl Disorder https://www.vinyldisorder.com/circle-stickers.html

**Comment by partytax** [comment]
May try to source from a local shop, though

**Comment by partytax** [comment]
100 2.5" circle vinyl stickers would be ~$108 from local printer

**Comment by fionadunne** [comment]
Very rough count of dots on Transit app gives 50 dots along 3B line and 
39 along 3a. Does that mean we need about 50*2=100 3B and 39*2=78 3a stickers? I don't know if there is one dot on the map per sign per direction or not.

**Comment by fionadunne** [comment]
Say we only do 3a and 3b stickers at first. Then at stops that are shared between 3a/3b and other lines, I suggest we not put any stickers at all rather than have it say 3a/3b and not 10 when it's really both.

**Comment by partytax** [comment]
I mean knowing the stop _is_ served by 3 would be better than not knowing that, even if it is served by other routes.

The status-quo is a complete lack of in-context information.

**Comment by partytax** [comment]
Made a personal task to order 3A and 3B stickers. @fionadunne @TimMagee Ok with separate 3A and 3B circles?

**Comment by fionadunne** [comment]
Yes I prefer separate 3a and 3b circles.
If you want to put 3a or 3 b stickers on stops served by other routes, I suggest we get stickers for those routes to just for those signs, looks like that might be:
1B X1
1A X3
9 X5
5 X1
(I have not double checked those counts)
Because when someone is looking for the 9 and they see a sign that says 3B and does not say 9, that is super confusing, and I think, worse than a blank sign.

**Comment by fionadunne** [comment]
> 100 2.5" circle vinyl stickers would be ~$108 from local printer

I would lean towards vinyl disorder for 3 times lower cost but up to you.

**Comment by fionadunne** [comment]
Tried to count dots on Google maps this time and now that makes me think 93 stickers of 3B and 84 of 3A. Or something like that...

**Comment by partytax** [comment]
Ok. Maybe best to 100 stickers for each of those 5 routes all at once.

$52.73 * 5 * 1.053 tax = $277.62

**Comment by partytax** [comment]
Considering this a bug rather than an enhancement because GLTC had "working" signs with route information and removed them.

**Comment by fionadunne** [comment]
> Ok. Maybe best to order 100 stickers for each of those 5 routes all at once.
> 
> $52.73 * 5 * 1.053 tax = $277.62

There is this option to just get 2 samples at a time in case you didn't see it https://www.vinyldisorder.com/custom-sample-sticker.html . Sounds fine to me either way.

**Comment by partytax** [comment]
Rode 3A the other week to determine if route is the same as GLTC map. 

On map, bus goes on Rivermont Avenue one way and Bedford Avenue the other way.

In reality, bus goes on Bedford Avenue both ways.

**Comment by partytax** [comment]
Made personal task to call GLTC customer service to ask about this

**Comment by partytax** [comment]
Stickers applied from transfer station to Rivermont Bridge for route 3A (and any other routes that pass 3A signs).

Exception is first set of stops on Buchanan Street, which have not had stickers applied yet.

**Comment by partytax** [comment]
Had a conversation with Wendell Watts II today and learned that Rivermont Avenue *IS* served by 3A outbound, but only Mo-Fr & Su and only on the first trip of the day. This will necessitate putting 3A stickers outbound on Rivermont Avenue between Bedford Avenue intersections and getting some qualifier stickers saying stuff like "FIRST TRIP ONLY", "MON-FRI", and "SUN".

![336158676-ecc28705-ae96-463d-98af-4b128d982ba4](https://github.com/Lynchburg-Urban-Network/lynchburg-road-issues/assets/29897671/44bf47a7-bca7-4bfc-934f-680abb5387b7)

**Comment by partytax** [comment]
It is done as of the other day!
