### ISSUE TITLE
Street lamp on pole 30B at around 1721 Campbell Ave is out

### ISSUE THREAD

**Issue by TimMagee** [Lynchburg-Urban-Network/lynchburg-road-issues#163]
The street lamp right by the old railroad crossing on Campbell Ave is out.

![IMG_20240210_204640509](https://github.com/Lynchburg-Urban-Network/lynchburg-road-issues/assets/11220851/5f5f51f4-b894-41b4-bf52-012fefdc0ca0)

https://www.openstreetmap.org/node/11395990628

**Comment by TimMagee** [comment]
I received a response from Appalachian Power:

> Dear Tim,
>
> Thank you for contacting us at [AppalachianPower.com.](http://www.appalachianpower.com/) 
>
>We have reported the street light out at 1721 Campbell Ave. The order number is 021461357. We appreciate you bringing this to our attention and will make repairs as soon as possible.
>
>If we can be of any further assistance, you are welcome to email us at customer_service@AEP.com. When emailing us, please include a copy of the original inquiry and subsequent responses.
>
> Sincerely,
>
> Katie B.

[Appalachian Power®](http://www.appalachianpower.com/)

**Comment by partytax** [comment]
@TimMagee Any update on this lamp?

**Comment by partytax** [comment]
made personal task to check if lamp still out

**Comment by partytax** [comment]
Lamp has been fixed!
