### ISSUE TITLE
Inbound bus stop #786419 on 12th Street near Polk Street is missing

### ISSUE THREAD

**Issue by TimMagee** [Lynchburg-Urban-Network/lynchburg-road-issues#187]
The bus stop sign is completely missing as shown in the attached photos
![IMG_20240331_173830276_HDR](https://github.com/Lynchburg-Urban-Network/lynchburg-road-issues/assets/11220851/a95cdf7c-981d-411b-a3d7-c8f7e75127cb)
![318303323-b9c71fe9-5edd-4bae-b50d-be870f48fa06](https://github.com/Lynchburg-Urban-Network/lynchburg-road-issues/assets/29897671/26f77224-bbc9-4386-9c5e-af701645287f)

**Comment by partytax** [comment]
Bus stop has ID 786419 and name "12th St. & Polk St. (Inbound)" in GTFS

**Comment by partytax** [comment]
Reported to Chris Poindexter, as I mentioned it offhand to him at an event and he said I should email him about it:

> Good afternoon. The missing bus stop sign I mentioned on 12th street has ID 786419 in GTFS file and is located at the intersection of Polk St. There's a metal mounting point on the ground, but no sign.
> 
> Please let me know who deals with these issues, as the Lynchburg Urban Network is conducting an extensive survey of GLTC bus stops and will need to submit dozens of maintenance requests (don't want to take up your time forwarding requests).
> 
> Thanks again for the opportunity to film the bikes on buses video, and for considering this request!
> 
> Nathan

**Comment by partytax** [comment]
Chris Poindexter sent me an email about something else, so responded inquiring about whether this has been reported:


> Thanks! You all did great with the edit.
> 
> By the way, were you able to send the info about the missing bus stop on 12th and Polk to the folks who deal with that?
> 
> Nathan

**Comment by partytax** [comment]
Chris Poindexter says it's replaced. Made personal task to verify.

**Comment by partytax** [comment]
Fixed! Needs bolts tightened a lot, but secure enough.

![signal-2024-05-09-164814_002](https://github.com/Lynchburg-Urban-Network/lynchburg-road-issues/assets/29897671/7e5a0466-365f-4aad-a646-f79754e8b7ed)
