### ISSUE TITLE
Blackwater Creek Trail head at Linkhorne Middle School has sign forbidding trail use after school gets out

### ISSUE THREAD

**Issue by partytax** [Lynchburg-Urban-Network/lynchburg-road-issues#4]
A sign at the Blackwater creek trailhead says that the trail is closed when school is getting off. I imagine it's to prevent the parking lot from being occupied with trailgoers at a busy school time, but why couldn't the parking be forbidden? In effect it says that children at that school are not permitted to bike home along the trail.

Need to recheck situation and get pictures.

**Comment by partytax** [comment]
Made personal task to visit trailhead and get pictures of sign and any surrounding signs

**Comment by partytax** [comment]
![signal-2023-06-03-122558_002](https://github.com/partytax/lynchburg-road-issues/assets/29897671/fded88a1-9e9a-4d27-a462-3d697444a8fc)

**Comment by partytax** [comment]
There's another duplicate sign along the driveway to the school.

**Comment by partytax** [comment]
Called Parks & Rec at 434 455 5858 and was transferred to Chris Higgins. He seemed to believe that the signs only forbid parking, when in reality they forbid trail use around school start and end times. He said he would look into the issue.

**Comment by partytax** [comment]
Made personal task to check if signs have been changed

**Comment by fionadunne** [comment]
These signs are still here as of yesterday

**Comment by partytax** [comment]
Going re-contact Parks & Rec new director

**Comment by fionadunne** [comment]
Today I spoke to Susanna Smith at ParksAnd Rec; she came in on the tail end of this project, and agrees the current signs are unfortunate especially because this trail is part of our 'Safe routes to school'. Parks and Rec worked together with the school when these signs were put in, and change would need to go through the school board. She suggests I and other members of the public call the school principal, and she will also talk to the person responsible for parks and rec trail signs in general (Howard Covey) to see if they have any other info.

**Comment by fionadunne** [comment]
Linkhorne middle principal says school itself has no involvement but that I can email her the details and she will forward on to Lynchburg City Schools to get the request on the right path.

**Comment by fionadunne** [comment]
Email sent.

**Comment by fionadunne** [comment]
Email sent.

**Comment by fionadunne** [comment]
Principal says she submitted my email, and I should now call to Reid Wodicka at Lynchburg City Schools. No answer today, will try another day.

**Comment by fionadunne** [comment]
Reid seems to agree it makes sense to do something about this, he will talk to facilities folks next week and get back to me.

**Comment by fionadunne** [comment]
No response from Reid Wodicka since we first talked a month ago. Called again and left a message a couple weeks ago and a couple days ago, but got no call back.

**Comment by fionadunne** [comment]
I see today that all three signs have now been removed! Don't know if any replacement is planned, haven't heard anything back lately.
