### ISSUE TITLE
Rebuilt intersections at Gristmill Drive, Graves Mill Road, and Forest Road have the beg buttons covered

### ISSUE THREAD

**Issue by TheFatCyclist** [Lynchburg-Urban-Network/lynchburg-road-issues#60]

**Comment by partytax** [comment]
https://www.openstreetmap.org/#map=18/37.37865/-79.24820
https://www.openstreetmap.org/#map=18/37.37566/-79.24925
![IMG_6337](https://github.com/partytax/lynchburg-road-issues/assets/29897671/ac21474a-e105-416c-8e3b-8632b302be1d)

**Comment by partytax** [comment]
@TheFatCyclist Contacted VDOT and received email from Len confirming that he's looking into it.

**Comment by partytax** [comment]
Email from Len:

”Hey, Andrew.

I have found out that there need to be signs posted along with the signals. The law requires that, once the beg signals are operational, there need to be signs informing drivers that they must yield to pedestrians. We can't have the signals without the signs. I'm checking on the timeline for receiving the signs. Once we have them, we will post them and activate the beg signals.

Let me know of any other questions. Thanks!"

**Comment by partytax** [comment]
Made personal task to check this, as I will be passing by soon.

**Comment by partytax** [comment]
Surveyed on 2023-10-01 and signals are still covered

**Comment by partytax** [comment]
Surveyed and signals are now in operation

**Comment by TheFatCyclist** [comment]
Signals and buttons have been activated. Item complete
